from __future__ import annotations

from pathlib import Path
import re
from typing import Iterable
from uuid import uuid4

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import get_settings
from app.models import Project, User
from app.schemas.file_system import FileNode

settings = get_settings()

STARTER_FILES = {
    "README.md": """# Syntrix Starter Web App

This sample project is created automatically so the workspace has real files to edit, preview, run, and deploy.
""",
    "index.html": """<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Syntrix Starter</title>
    <link rel="stylesheet" href="./styles.css" />
  </head>
  <body>
    <main class="page-shell">
      <section class="hero-card">
        <p class="eyebrow">Generated by Syntrix AI</p>
        <h1>Build, preview, iterate, and deploy from one workspace.</h1>
        <p class="body-copy">
          This starter project exists so Syntrix can demonstrate file editing, terminal commands,
          live preview, agent planning, and deployment export on day one.
        </p>
        <button id="launch-btn">Launch momentum</button>
        <p id="status" class="status-pill">Waiting for action</p>
      </section>
    </main>
    <script src="./app.js"></script>
  </body>
</html>
""",
    "styles.css": """:root {
  color-scheme: dark;
  --bg-1: #040814;
  --bg-2: #071324;
  --card: rgba(10, 20, 42, 0.82);
  --border: rgba(255,255,255,0.12);
  --accent-1: #57e4c2;
  --accent-2: #6dd3ff;
  --text: #f7f9ff;
  --muted: #9fb2d8;
}

* { box-sizing: border-box; }
body {
  margin: 0;
  min-height: 100vh;
  font-family: "Segoe UI Variable", "Bahnschrift", sans-serif;
  background:
    radial-gradient(circle at top left, rgba(87,228,194,0.15), transparent 28%),
    radial-gradient(circle at top right, rgba(109,211,255,0.18), transparent 22%),
    linear-gradient(180deg, var(--bg-2), var(--bg-1));
  color: var(--text);
}
.page-shell {
  min-height: 100vh;
  display: grid;
  place-items: center;
  padding: 32px;
}
.hero-card {
  width: min(760px, 100%);
  border: 1px solid var(--border);
  background: var(--card);
  border-radius: 32px;
  padding: 40px;
  box-shadow: 0 24px 80px rgba(0,0,0,0.32);
  backdrop-filter: blur(18px);
}
.eyebrow {
  letter-spacing: 0.22em;
  text-transform: uppercase;
  color: var(--accent-2);
  font-size: 12px;
}
h1 {
  font-size: clamp(2rem, 6vw, 4rem);
  line-height: 1.05;
  margin: 12px 0;
}
.body-copy {
  color: var(--muted);
  line-height: 1.8;
  font-size: 1rem;
}
button {
  margin-top: 24px;
  border: none;
  border-radius: 999px;
  padding: 14px 22px;
  font-weight: 600;
  background: linear-gradient(135deg, var(--accent-1), var(--accent-2));
  color: #04111f;
  cursor: pointer;
}
.status-pill {
  margin-top: 18px;
  display: inline-flex;
  padding: 8px 14px;
  border-radius: 999px;
  background: rgba(255,255,255,0.06);
  color: var(--muted);
}
""",
    "app.js": """const button = document.getElementById("launch-btn");
const status = document.getElementById("status");

button?.addEventListener("click", () => {
  const messages = [
    "Planner agent mapped the next sprint.",
    "Coding agent prepared the first file patch.",
    "Debug agent is watching for regressions.",
    "Terminal agent is ready to run the next command."
  ];

  const message = messages[Math.floor(Math.random() * messages.length)];
  status.textContent = message;
});
""",
    "vercel.json": """{
  "framework": null,
  "buildCommand": "",
  "outputDirectory": ".",
  "rewrites": [{ "source": "/(.*)", "destination": "/index.html" }]
}
""",
    "render.yaml": """services:
  - type: web
    name: syntrix-generated-app
    env: static
    buildCommand: ""
    staticPublishPath: .
""",
    "Dockerfile": """FROM nginx:alpine
COPY . /usr/share/nginx/html
EXPOSE 80
"""
}


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug or "project"


def get_backend_root() -> Path:
    return Path(__file__).resolve().parents[2]


def get_workspace_root() -> Path:
    return get_backend_root() / settings.workspace_root


def ensure_workspace_root() -> Path:
    root = get_workspace_root()
    root.mkdir(parents=True, exist_ok=True)
    return root


def ensure_project_directory(project: Project) -> Path:
    root = Path(project.root_path)
    root.mkdir(parents=True, exist_ok=True)
    return root


def seed_project_directory(project_root: Path, project_name: str) -> None:
    for relative_path, content in STARTER_FILES.items():
        target = project_root / relative_path
        if not target.exists():
            target.write_text(content.replace("Syntrix Starter", project_name), encoding="utf-8")


async def create_project(
    *,
    session: AsyncSession,
    user: User,
    name: str,
    description: str,
) -> Project:
    base_root = ensure_workspace_root()
    slug = slugify(name)
    project_root = base_root / f"{slug}-{user.id[:8]}-{uuid4().hex[:8]}"
    project = Project(
        user_id=user.id,
        name=name,
        slug=slug,
        description=description,
        root_path=str(project_root),
    )
    session.add(project)
    await session.flush()
    ensure_project_directory(project)
    seed_project_directory(project_root, name)
    return project


async def ensure_workspace_samples() -> None:
    ensure_workspace_root()


async def ensure_default_project_for_user(session: AsyncSession, user: User) -> Project:
    result = await session.execute(select(Project).where(Project.user_id == user.id).limit(1))
    project = result.scalar_one_or_none()
    if project is not None:
        ensure_project_directory(project)
        seed_project_directory(Path(project.root_path), project.name)
        return project

    project = await create_project(
        session=session,
        user=user,
        name="Syntrix Starter Workspace",
        description="Default starter workspace for chat, file, preview, and terminal flows.",
    )
    await session.commit()
    await session.refresh(project)
    return project


def resolve_project_path(project: Project, relative_path: str) -> Path:
    root = ensure_project_directory(project).resolve()
    target = (root / relative_path).resolve()
    if root not in target.parents and target != root:
        raise ValueError("Requested path is outside the project root.")
    return target


def build_file_tree(root: Path, base: Path | None = None) -> list[FileNode]:
    base = base or root
    nodes: list[FileNode] = []

    for child in sorted(root.iterdir(), key=lambda item: (item.is_file(), item.name.lower())):
        if child.name.startswith(".") and child.name not in {".env.example"}:
            continue

        relative = child.relative_to(base).as_posix()
        if child.is_dir():
            nodes.append(
                FileNode(
                    name=child.name,
                    path=relative,
                    type="directory",
                    children=build_file_tree(child, base),
                )
            )
        else:
            nodes.append(FileNode(name=child.name, path=relative, type="file", children=[]))

    return nodes


def detect_language(path: str) -> str:
    extension_map = {
        ".py": "python",
        ".ts": "typescript",
        ".tsx": "typescript",
        ".js": "javascript",
        ".jsx": "javascript",
        ".json": "json",
        ".html": "html",
        ".css": "css",
        ".md": "markdown",
        ".yml": "yaml",
        ".yaml": "yaml",
        ".sql": "sql",
    }
    suffix = Path(path).suffix.lower()
    return extension_map.get(suffix, "plaintext")


def inline_preview_html(project: Project) -> tuple[str, str]:
    project_root = ensure_project_directory(project)
    entry_path = project_root / settings.preview_entry_file
    if not entry_path.exists():
        return ("<html><body><h1>No preview entry file found.</h1></body></html>", settings.preview_entry_file)

    html = entry_path.read_text(encoding="utf-8")

    stylesheet_path = project_root / "styles.css"
    if stylesheet_path.exists():
        stylesheet_tag = f"<style>{stylesheet_path.read_text(encoding='utf-8')}</style>"
        html = html.replace('<link rel="stylesheet" href="./styles.css" />', stylesheet_tag)

    script_path = project_root / "app.js"
    if script_path.exists():
        script_tag = f"<script>{script_path.read_text(encoding='utf-8')}</script>"
        html = html.replace('<script src="./app.js"></script>', script_tag)

    return (html, settings.preview_entry_file)


def list_relative_files(project: Project) -> list[str]:
    root = ensure_project_directory(project)
    return [
        path.relative_to(root).as_posix()
        for path in root.rglob("*")
        if path.is_file() and not any(part.startswith(".") for part in path.relative_to(root).parts)
    ]
